FROM python:3.8-slim

# working dir
WORKDIR /opt/ml/processing

# install dependencies
RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    && rm -rf /var/lib/apt/lists/*

# install python packages
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
